site_name: Portalis Documentation
site_description: GPU-Accelerated Python to Rust to WASM Translation Platform
site_author: Portalis Team
site_url: https://portalis.dev

repo_name: portalis/portalis
repo_url: https://github.com/portalis/portalis
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started.md
  - User Guide:
    - CLI Reference: cli-reference.md
    - Python Compatibility: python-compatibility.md
    - Troubleshooting: troubleshooting.md
    - Assessment Tools: assessment.md
  - Architecture:
    - Overview: architecture.md
  - Deployment:
    - Docker Compose: deployment/docker-compose.md
    - Kubernetes: deployment/kubernetes.md
  - Security & Compliance:
    - Security Guide: security.md
    - Compliance: compliance.md
  - Performance:
    - Performance Tuning: performance.md
  - API Reference:
    - REST API: api-reference.md
  - Beta Program:
    - Beta Program Guide: beta-program.md
    - Onboarding Checklist: onboarding-checklist.md
  - Monitoring:
    - Monitoring Guide: monitoring.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/portalis/portalis
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/portalis/portalis
  analytics:
    provider: google
    property: G-XXXXXXXXXX

copyright: Copyright &copy; 2025 Portalis Team
