# DCGM Exporter Configuration for Portalis DGX Cloud
# Collects GPU metrics from NVIDIA GPUs

apiVersion: v1
kind: ConfigMap
metadata:
  name: dcgm-exporter-config
  namespace: portalis
data:
  dcgm-exporter-config.csv: |
    # Format: DCGM_FI metric name, Prometheus metric name
    # GPU Utilization
    DCGM_FI_DEV_GPU_UTIL, dcgm_gpu_utilization_percent
    DCGM_FI_DEV_MEM_COPY_UTIL, dcgm_gpu_memory_copy_utilization_percent
    DCGM_FI_DEV_ENC_UTIL, dcgm_gpu_encoder_utilization_percent
    DCGM_FI_DEV_DEC_UTIL, dcgm_gpu_decoder_utilization_percent

    # Memory
    DCGM_FI_DEV_FB_USED, dcgm_gpu_memory_used_bytes
    DCGM_FI_DEV_FB_FREE, dcgm_gpu_memory_free_bytes
    DCGM_FI_DEV_FB_TOTAL, dcgm_gpu_memory_total_bytes

    # Temperature
    DCGM_FI_DEV_GPU_TEMP, dcgm_gpu_temperature_celsius
    DCGM_FI_DEV_MEMORY_TEMP, dcgm_gpu_memory_temperature_celsius

    # Power
    DCGM_FI_DEV_POWER_USAGE, dcgm_gpu_power_usage_watts
    DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION, dcgm_gpu_total_energy_consumption_joules

    # Clocks
    DCGM_FI_DEV_SM_CLOCK, dcgm_gpu_sm_clock_mhz
    DCGM_FI_DEV_MEM_CLOCK, dcgm_gpu_memory_clock_mhz

    # PCIe
    DCGM_FI_DEV_PCIE_TX_THROUGHPUT, dcgm_gpu_pcie_tx_bytes_per_second
    DCGM_FI_DEV_PCIE_RX_THROUGHPUT, dcgm_gpu_pcie_rx_bytes_per_second
    DCGM_FI_DEV_PCIE_REPLAY_COUNTER, dcgm_gpu_pcie_replay_counter

    # NVLink
    DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL, dcgm_gpu_nvlink_bandwidth_bytes_per_second

    # XID Errors
    DCGM_FI_DEV_XID_ERRORS, dcgm_gpu_xid_errors

    # Compute Processes
    DCGM_FI_DEV_COMPUTE_PIDS, dcgm_gpu_compute_processes

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: portalis
  labels:
    app: dcgm-exporter
spec:
  selector:
    matchLabels:
      app: dcgm-exporter
  template:
    metadata:
      labels:
        app: dcgm-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9400"
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: dcgm-exporter
        image: nvcr.io/nvidia/k8s/dcgm-exporter:3.1.8-3.1.5-ubuntu22.04
        ports:
        - name: metrics
          containerPort: 9400
        env:
        - name: DCGM_EXPORTER_LISTEN
          value: ":9400"
        - name: DCGM_EXPORTER_KUBERNETES
          value: "true"
        - name: DCGM_EXPORTER_INTERVAL
          value: "10000"  # 10 seconds
        volumeMounts:
        - name: config
          mountPath: /etc/dcgm-exporter
        - name: pod-resources
          mountPath: /var/lib/kubelet/pod-resources
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
      volumes:
      - name: config
        configMap:
          name: dcgm-exporter-config
      - name: pod-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: portalis
  labels:
    app: dcgm-exporter
spec:
  type: ClusterIP
  clusterIP: None  # Headless service
  ports:
  - name: metrics
    port: 9400
    targetPort: 9400
    protocol: TCP
  selector:
    app: dcgm-exporter

---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter
  namespace: portalis
  labels:
    app: dcgm-exporter
spec:
  selector:
    matchLabels:
      app: dcgm-exporter
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
