apiVersion: v1
kind: Secret
metadata:
  name: portalis-rust-transpiler-secrets
  namespace: portalis-deployment
  labels:
    app: portalis-rust-transpiler
    component: transpiler
type: Opaque
stringData:
  # API keys for authentication
  api-keys: |
    client1:sk-abc123def456
    client2:sk-xyz789uvw012
    internal:sk-int999888777

  # Triton credentials (if needed)
  triton-api-key: "triton-secret-key-placeholder"

  # NeMo service credentials
  nemo-api-key: "nemo-secret-key-placeholder"

  # Database credentials (if using persistent state)
  db-username: "portalis"
  db-password: "changeme-in-production"

  # Redis credentials (if using caching)
  redis-password: "changeme-redis-password"

  # JWT secret for token signing
  jwt-secret: "changeme-jwt-secret-256bit"

  # Encryption keys
  encryption-key: "changeme-encryption-key"

---
apiVersion: v1
kind: Secret
metadata:
  name: portalis-registry-credentials
  namespace: portalis-deployment
  labels:
    app: portalis-rust-transpiler
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZ2MubnZpZGlhLmNvbSI6eyJ1c2VybmFtZSI6IiRvYXV0aHRva2VuIiwicGFzc3dvcmQiOiJwbGFjZWhvbGRlciIsImF1dGgiOiJKRzloZFhSb2RHOXJaVzQ2Y0d4aFkyVm9iMnhrWlhJPSJ9fX0=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portalis-rust-transpiler-env
  namespace: portalis-deployment
  labels:
    app: portalis-rust-transpiler
    component: transpiler
data:
  # Non-sensitive environment variables
  SERVICE_VERSION: "1.0.0"
  API_VERSION: "v1"
  ENABLE_SWAGGER: "true"
  ENABLE_DOCS: "true"
  CORS_ORIGINS: "https://portalis.dev,https://*.portalis.dev"
  MAX_WORKERS: "4"
  WORKER_TIMEOUT: "300"
